# Generated by Django 5.0.6 on 2024-06-03 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'Household',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=40)),
                ('LastName', models.CharField(max_length=40)),
                ('Birthday', models.DateField()),
                ('IsAlive', models.BooleanField(default=True)),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Non-binary', 'Non-binary')], max_length=11, null=True)),
                ('Pronouns', models.CharField(blank=True, max_length=20, null=True)),
                ('Email', models.EmailField(blank=True, max_length=100, null=True)),
                ('Cell', models.CharField(blank=True, max_length=20, null=True)),
                ('CityBorn', models.CharField(blank=True, max_length=30, null=True)),
                ('StateBorn', models.CharField(blank=True, max_length=30, null=True)),
                ('CountryBorn', models.CharField(blank=True, max_length=30, null=True)),
                ('CityCurrent', models.CharField(blank=True, max_length=30, null=True)),
                ('StateCurrent', models.CharField(blank=True, max_length=30, null=True)),
                ('CountryCurrent', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'Person',
                'ordering': ['FirstName', 'LastName'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('PhotoID', models.AutoField(primary_key=True, serialize=False)),
                ('PhotoPath', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Photo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('PersonID', models.ForeignKey(db_column='PersonID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='common.person')),
                ('Interest', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'Interests',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Spouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Spouse1ID', models.ForeignKey(db_column='Spouse1ID', on_delete=django.db.models.deletion.CASCADE, related_name='spouse1_set', to='common.person')),
                ('Spouse2ID', models.ForeignKey(db_column='Spouse2ID', on_delete=django.db.models.deletion.CASCADE, related_name='spouse2_set', to='common.person')),
            ],
            options={
                'db_table': 'Spouse',
                'unique_together': {('Spouse1ID', 'Spouse2ID')},
            },
        ),
    ]
