# Generated by Django 5.0.4 on 2024-06-02 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Household',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'Interests',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=40)),
                ('LastName', models.CharField(max_length=40)),
                ('birthday', models.DateField()),
                ('IsAlive', models.BooleanField(default=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Non-binary', 'Non-binary')], max_length=11, null=True)),
                ('pronouns', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('cell', models.CharField(blank=True, max_length=20, null=True)),
                ('CityBorn', models.CharField(blank=True, max_length=30, null=True)),
                ('StateBorn', models.CharField(blank=True, max_length=30, null=True)),
                ('CountryBorn', models.CharField(blank=True, max_length=30, null=True)),
                ('CityCurrent', models.CharField(blank=True, max_length=30, null=True)),
                ('StateCurrent', models.CharField(blank=True, max_length=30, null=True)),
                ('CountryCurrent', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'Person',
                'ordering': ['FirstName', 'LastName'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('photo_id', models.AutoField(primary_key=True, serialize=False)),
                ('photo_path', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Photo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Spouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spouse1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spouse1', to='common.person')),
                ('spouse2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spouse2', to='common.person')),
            ],
            options={
                'db_table': 'Spouse',
                'unique_together': {('spouse1', 'spouse2')},
            },
        ),
    ]
