# Generated by Django 5.0.4 on 2024-06-03 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='spouse',
            unique_together={('Spouse1ID', 'Spouse2ID')},
        ),
        migrations.AddField(
            model_name='spouse',
            name='Spouse1ID',
            field=models.ForeignKey(db_column='Spouse1ID', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='spouse1_set', to='common.person'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spouse',
            name='Spouse2ID',
            field=models.ForeignKey(db_column='Spouse2ID', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='spouse2_set', to='common.person'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='spouse',
            name='spouse1',
        ),
        migrations.RemoveField(
            model_name='spouse',
            name='spouse2',
        ),
    ]
