# Generated by Django 5.0.6 on 2024-06-01 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('birthday', models.DateField()),
                ('is_alive', models.BooleanField(default=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Non-binary', 'Non-binary')], max_length=11, null=True)),
                ('pronouns', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('cell', models.CharField(blank=True, max_length=20, null=True)),
                ('city_born', models.CharField(blank=True, max_length=30, null=True)),
                ('state_born', models.CharField(blank=True, max_length=30, null=True)),
                ('country_born', models.CharField(blank=True, max_length=30, null=True)),
                ('city_current', models.CharField(blank=True, max_length=30, null=True)),
                ('state_current', models.CharField(blank=True, max_length=30, null=True)),
                ('country_current', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'Person',
                'managed': False,
            },
        ),
    ]
